actions notifications chore

diff --git a/.github/workflows/panel/panelApiHealthcheck.yml b/.github/workflows/panel/panelApiHealthcheck.yml
--- a/.github/workflows/panel/panelApiHealthcheck.yml
+++ b/.github/workflows/panel/panelApiHealthcheck.yml
@@ -27,4 +27,14 @@ jobs:
         run: npm install
 
       - name: Run panel app healthcheck
-        run: npm run panel-app-api-health-check
+        id: run_healthcheck
+        run: |
+          npm run panel-app-api-health-check
+          echo "exit_code=$?" >> $GITHUB_OUTPUT
+          exit 0
+
+#      - name: Notify on failure
+#        if: steps.run_healthcheck.outputs.exit_code != '0'
+#        run: |
+#          TEXT=$(echo "❌ Panel App Health Check failed, details: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" | jq -s -R -r @uri)
+#          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=$TEXT"
