fixes

diff --git a/.github/workflows/panelApiHealthcheck.yml b/.github/workflows/panelApiHealthcheck.yml
--- a/.github/workflows/panelApiHealthcheck.yml
+++ b/.github/workflows/panelApiHealthcheck.yml
@@ -38,16 +38,19 @@ jobs:
             "returnSecureToken": true
           }')
 
-          STATUS_CODE=$(echo "$RESPONSE" | jq -r '.error.message // "No Error Message"')
-          echo "HTTP Status: $STATUS_CODE"
-          echo "API Response: $RESPONSE"
+          # Checking for response errors or success
+          ERROR_MESSAGE=$(echo "$RESPONSE" | jq -r '.error.message // "No Error Message"')
+          if [ "$ERROR_MESSAGE" != "No Error Message" ]; then
+            echo "Error: $ERROR_MESSAGE"
+            exit 1
+          fi
 
           TOKEN=$(echo "$RESPONSE" | jq -r '.idToken')
 
           if [ "$TOKEN" != "null" ]; then
-            echo "TOKEN: $TOKEN"
+            echo "ID Token: $TOKEN"
           else
-            echo "Failed to retrieve token: $STATUS_CODE"
+            echo "Failed to retrieve ID token"
             exit 1
           fi
         shell: bash
